name: nearm-awesome-masa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.23.5
  - streamlit
  - faiss-cpu
  - pip
  - pip:
    - langchain
    - langgraph
    - langchain-openai
    - langchain-core
    - langchain-huggingface
    - langchain-community
    - python-dotenv
    - streamlit-extras
    - pydantic
    - transformers
    - sentence-transformers
