api_endpoint: 'http://localhost:8080/api/v1/data/twitter/tweets/recent' 
headers:
  accept: 'application/json'
  Content-Type: 'application/json'

# Query settings
account: 'NEARMobile_app'  # The account whose followed list we want to fetch
tweets_per_request: 70

# Add start_date and end_date
start_date: '2024-10-8'
end_date: '2024-11-8'
days_per_iteration: 7

# File settings
data_directory: 'data/NEARMobileAppFollowedAccounts'

# Timing settings
retry_delay: 1111  # 16 minutes in seconds
request_delay: 21  # 15 seconds between requests

# Logging settings
log_level: 'INFO'
log_format: '%(asctime)s - %(levelname)s - %(message)s'

# NEW
max_retries: 5
request_timeout: 60
