# API settings
#api_endpoint: 'http://localhost:8080/api/v1/data/twitter/tweets/recent'
api_endpoint: 'http://localhost:8080/api/v1/data/twitter/tweets/recent'
headers:
  accept: 'application/json'
  Content-Type: 'application/json'

# Query settings
#query: '(from: )'
tweets_per_request: 30

# Add start_date and end_date
start_date: '2024-08-10'
end_date: '2024-10-29'
days_per_iteration: 2

# File settings
data_directory: 'data/LaLigaEquipos'

# Timing settings
retry_delay: 1111  # 16 minutes in seconds
request_delay: 33  # 15 seconds between requests

# Logging settings
log_level: 'INFO'
log_format: '%(asctime)s - %(levelname)s - %(message)s'


# NEW
max_retries: 33
request_timeout: 60